PR #2/5 Astolfo feature/builtin-macro
godot-rust/gdextension pull request #66
Opened 2023-01-16 20:33 UTC by RealAstolfo

Co-Authored-By: Thomas ten Cate <ttencate@gmail.com>

These are the macros created by ttencate, and is meant to be merged after #65,

this pr implements "Real" to be closer to upstream godot's C++ internals, also adds a vector macro to construct vector2 through vector4 easier.

2023-01-16 23:01 UTC, Bromeon requested changes
Thanks for these macros!

I think the macros are suitable to avoid code duplication for cases that are very boiler-platey or trivial. However, this PR goes a bit too far in some places, as it forcibly reuses code even if that code is significantly different. This necessitates extra helpers to make the reuse work, making the logic non-local and harder to read.

The use of `paste!` for snake_case conversion + concatenation is quite clever! 😎 
I hope it doesn't affect compile times too badly.

2023-01-16 23:14 UTC, Bromeon commented on godot-core/src/builtin/vector_macros.rs
> +        $component_type:ty,
Maybe this could be called `scalar` instead of `component_type`.

2023-01-17 08:20 UTC, ttencate commented on godot-core/src/builtin/real.rs
> +    /// not supported yet.
I seem to recall that the engine uses `float` in some places even if compiled with `precision=double`, so it seemed smart to make people think about this every time they use a floating-point type in gdextension. However, there's no guarantee that adding `Real` prematurely will do this. Removing it.

2023-01-17 08:22 UTC, ttencate commented on godot-core/src/builtin/vector_macros.rs
> +            }
Alright, adding `from_glam` and `as_glam` instead.

2023-01-17 08:23 UTC, ttencate commented on godot-core/src/builtin/vector_macros.rs
> +}
I was following the engine API here, but they do it with conversion constructors `Vector2(Vector2i from)`. That's a better approach indeed.

2023-01-17 08:24 UTC, ttencate commented on godot-core/src/builtin/vector_macros.rs
> +            }
... which means not wrapping `glam`. (Or `Deref`'ing to `glam` but that still exposes `glam` in the public API which we don't want.)

2023-01-17 09:54 UTC, Bromeon commented on godot-core/src/builtin/vector_macros.rs
> +}
We could do something like:
```rs
Vector2i::from_float_lossy(v: Vector2)
Vector2::from_int(v: Vector2i)
```

2023-01-17 09:57 UTC, Bromeon commented on godot-core/src/builtin/vector_macros.rs
> +            }
If you return a copy, maybe use `to_glam()`. I think the Rust convention for "as_" is to return references.

2023-01-17 11:57 UTC, ttencate commented
Since @RealAstolfo allowed me to take this PR back, I've created a new PR: #71.

There are a lot of changes compared to this one, to address @Bromeon's comments above. Most notably we now have public x/y/z fields, which changes how the rest of the API is implemented. @RealAstolfo This will probably cause you some merge pain; I'm very sorry about that.

2023-01-18 13:43 UTC, Bromeon commented on godot-core/src/builtin/real.rs
> +    /// not supported yet.
Ohh, even better! I seem to have missed it 😬

Thanks for the input! Support for `double` is then something we might consider for godot-rust, although I'd like to get the core features ready first.

2023-01-20 22:51 UTC, Bromeon commented
Now implemented in #71. Thanks a lot to both of you, the discussion of potential vector designs was really fruitful! ❤️

2023-01-20 22:51 UTC, closed without merging